version: "3.9"

services:
  couchbase:
    image: couchbase:community
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    environment:
      COUCHBASE_ADMIN_USERNAME: admin
      COUCHBASE_ADMIN_PASSWORD: 123456
    volumes:
      - couchbase_data:/opt/couchbase/var
      - ./couchbase/init.sh:/init.sh
    command: ["bash", "/init.sh"]
    networks:
      - todo_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/ui/index.html"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: oguzhanerten/todo-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      couchbase:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - todo_net
    restart: always

  frontend:
    image: oguzhanerten/todo-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo_net
    restart: unless-stopped

volumes:
  couchbase_data:

networks:
  todo_net:
    driver: bridge